<?php

namespace AppBundle\Repository;

/**
 * TestEntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestEntRepository extends \Doctrine\ORM\EntityRepository
{
}
